server:
  port: 8080
spring:
  application:
    name: bxh
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: namespaceId
  devtools:
    restart:
      enabled: true
logging:
  level:
    root: info

bxh:
  info:
    age: 27
    score: 100
    weight: 120
    heigth: 123
